exports.testClubs = [
  { name: "club-01", purpose: "purpose-01" },
  { name: "club-02", purpose: "purpose-02" },
  { name: "club-03", purpose: "purpose-03" },
  { name: "club-04", purpose: "purpose-04" },
  { name: "club-05", purpose: "purpose-05" },
  { name: "club-06", purpose: "purpose-06" },
  { name: "club-07", purpose: "purpose-07" },
  { name: "club-08", purpose: "purpose-08" },
  { name: "club-09", purpose: "purpose-09" },
  { name: "club-10", purpose: "purpose-10" },
  { name: "club-11", purpose: "purpose-11" },
  { name: "club-12", purpose: "purpose-12" },
  { name: "club-13", purpose: "purpose-13" },
  { name: "club-14", purpose: "purpose-14" },
  { name: "club-15", purpose: "purpose-15" },
  { name: "club-16", purpose: "purpose-16" },
  { name: "club-17", purpose: "purpose-17" },
  { name: "club-18", purpose: "purpose-18" },
  { name: "club-19", purpose: "purpose-19" },
  { name: "club-20", purpose: "purpose-20" },
  { name: "club-21", purpose: "purpose-21" },
  { name: "club-22", purpose: "purpose-22" },
  { name: "club-23", purpose: "purpose-23" },
  { name: "club-24", purpose: "purpose-24" },
  { name: "club-25", purpose: "purpose-25" },
  { name: "club-26", purpose: "purpose-26" },
  { name: "club-27", purpose: "purpose-27" },
  { name: "club-28", purpose: "purpose-28" },
  { name: "club-29", purpose: "purpose-29" },
  { name: "club-30", purpose: "purpose-30" },
  { name: "club-31", purpose: "purpose-31" },
  { name: "club-32", purpose: "purpose-32" },
  { name: "club-33", purpose: "purpose-33" },
  { name: "club-34", purpose: "purpose-34" },
  { name: "club-35", purpose: "purpose-35" },
  { name: "club-36", purpose: "purpose-36" },
  { name: "club-37", purpose: "purpose-37" },
  { name: "club-38", purpose: "purpose-38" },
  { name: "club-39", purpose: "purpose-39" },
  { name: "club-40", purpose: "purpose-40" },
  { name: "club-41", purpose: "purpose-41" },
  { name: "club-42", purpose: "purpose-42" },
  { name: "club-43", purpose: "purpose-43" },
  { name: "club-44", purpose: "purpose-44" },
  { name: "club-45", purpose: "purpose-45" },
  { name: "club-46", purpose: "purpose-46" },
  { name: "club-47", purpose: "purpose-47" },
  { name: "club-48", purpose: "purpose-48" },
  { name: "club-49", purpose: "purpose-49" },
  { name: "club-50", purpose: "purpose-50" },
];

exports.basicClubs = [
  { name: "club-dogs", purpose: "Talk about Dogs." },
  { name: "club-cats", purpose: "Talk about Cats." },
  { name: "club-movies", purpose: "Talk about Movies." }
];
