exports.testClubs = [
  { name: "club-dogs", purpose: "Talk about Dogs." },
	{ name: "club-cats", purpose: "Talk about Cats." },
	{ name: "club-movies", purpose: "Talk about Movies." }
];

exports.gsbClubs = [
	{ name: "gc_adam_smith_society", purpose: "" },
	{ name: "gc_africa_business", purpose: "" },
	{ name: "gc_arts_media_entertainment", purpose: "" },
	{ name: "gc_asia_business_student_association", purpose: "" },
	{ name: "gc_basketball", purpose: "" },
	{ name: "gc_big_ideas", purpose: "" },
	{ name: "gc_black_business_student_association", purpose: "" },
	{ name: "gc_business_in_india", purpose: "" },
	{ name: "gc_cannabis_business", purpose: "" },
	{ name: "gc_catholic_student_association", purpose: "" },
	{ name: "gc_challenge_for_charity", purpose: "" },
	{ name: "gc_christians_in_business", purpose: "" },
	{ name: "gc_education", purpose: "" },
	{ name: "gc_energy", purpose: "" },
	{ name: "gc_entrepreneur", purpose: "" },
	{ name: "gc_epicureans_at_the_gsb", purpose: "" },
	{ name: "gc_europe", purpose: "" },
	{ name: "gc_finance_investment", purpose: "" },
	{ name: "gc_food_agribusiness", purpose: "" },
	{ name: "gc_friends_of_talk", purpose: "" },
	{ name: "gc_golf", purpose: "" },
	{ name: "gc_government_politics", purpose: "" },
	{ name: "gc_greater_china_business", purpose: "" },
	{ name: "gc_gsb_aerospace_business", purpose: "" },
	{ name: "gc_gsb_band", purpose: "" },
	{ name: "gc_gsb_game", purpose: "" },
	{ name: "gc_gsb_gives_back", purpose: "" },
	{ name: "gc_gsb_pride", purpose: "" },
	{ name: "gc_gsb_show", purpose: "" },
	{ name: "gc_gsb_shred", purpose: "" },
	{ name: "gc_health_care", purpose: "" },
	{ name: "gc_high_tech", purpose: "" },
	{ name: "gc_hispanic_business_student_association", purpose: "" },
	{ name: "gc_improvisational_theater_troupe", purpose: "" },
	{ name: "gc_jewish_business_student_association", purpose: "" },
	{ name: "gc_latin_american_student_association", purpose: "" },
	{ name: "gc_management_consulting", purpose: "" },
	{ name: "gc_marketing", purpose: "" },
	{ name: "gc_middle_east_north_africa", purpose: "" },
	{ name: "gc_outdoor_adventures", purpose: "" },
	{ name: "gc_private_equity", purpose: "" },
	{ name: "gc_product_design_manufacturing", purpose: "" },
	{ name: "gc_real_estate", purpose: "" },
	{ name: "gc_retail", purpose: "" },
	{ name: "gc_rugby", purpose: "" },
	{ name: "gc_soccer", purpose: "" },
	{ name: "gc_social_innovation", purpose: "" },
	{ name: "gc_sports_management", purpose: "" },
	{ name: "gc_sustainable_business", purpose: "" },
	{ name: "gc_texas", purpose: "" },
	{ name: "gc_travel_hospitality", purpose: "" },
	{ name: "gc_venture_capital", purpose: "" },
	{ name: "gc_veterans", purpose: "" },
	{ name: "gc_wellbeing", purpose: "" },
	{ name: "gc_wine_circle", purpose: "" },
	{ name: "gc_women_in_management", purpose: "" }
];

